{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "BasePlugin",
    "version": "0.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.8.jar",
          "url": "BasePlugin-0.3.8.jar",
          "size": 10659,
          "sha512": "3853ae14eee89b14ea6ef70305d337c8619a6402da19975463cf3e4b21e078b7370ae682fee008f9af0778d2ba74fe9f738da5c2c59f492507e2d866d0ff2b85",
          "sha256": "5b35371be39b4b91b61ba828ad36f294dcb439ea493e539b7a5cbe455312ab18",
          "sha1": "806f13275e2e4b2783de13b0208228fbfe00389d",
          "md5": "1115b491746f859cb0207287a1db14f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.8.jar",
          "url": "BasePlugin-0.3.8.jar",
          "size": 10659,
          "sha512": "3853ae14eee89b14ea6ef70305d337c8619a6402da19975463cf3e4b21e078b7370ae682fee008f9af0778d2ba74fe9f738da5c2c59f492507e2d866d0ff2b85",
          "sha256": "5b35371be39b4b91b61ba828ad36f294dcb439ea493e539b7a5cbe455312ab18",
          "sha1": "806f13275e2e4b2783de13b0208228fbfe00389d",
          "md5": "1115b491746f859cb0207287a1db14f7"
        }
      ]
    }
  ]
}
