{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "BasePlugin",
    "version": "0.3.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.11.jar",
          "url": "BasePlugin-0.3.11.jar",
          "size": 10659,
          "sha512": "0709526fa1fe2eeda5e1779dcd4d92e1e4db4890c2448d34649a7096f5173ab9b29e52d265655f463db85458a679f6a365041dabea5b354bb0559a66c7172f98",
          "sha256": "e829f002e3e504c5067f742c59eeb585a4883cbafe609f1e88881eb614031d68",
          "sha1": "17a5f1552ec626d9b74adbad37a11720d2e9df93",
          "md5": "a59bda69da26a837afb80b40806c340a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.11.jar",
          "url": "BasePlugin-0.3.11.jar",
          "size": 10659,
          "sha512": "0709526fa1fe2eeda5e1779dcd4d92e1e4db4890c2448d34649a7096f5173ab9b29e52d265655f463db85458a679f6a365041dabea5b354bb0559a66c7172f98",
          "sha256": "e829f002e3e504c5067f742c59eeb585a4883cbafe609f1e88881eb614031d68",
          "sha1": "17a5f1552ec626d9b74adbad37a11720d2e9df93",
          "md5": "a59bda69da26a837afb80b40806c340a"
        }
      ]
    }
  ]
}
