{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "hook-method-plugin",
    "version": "0.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "hook-method-plugin-0.3.13.jar",
          "url": "hook-method-plugin-0.3.13.jar",
          "size": 25963,
          "sha512": "46445510f8c3ac5b289fb66e36a302793befa0f8b2bfa47e6ed342185dcf16109467b95e114bd82aa6a2c8fe579d988ff79e5b62eb3ffedef3efd55482ab0ab6",
          "sha256": "96351cec57ecb453fe46bab0901f2681b155e7dee79f453899126e5e4adb1cd4",
          "sha1": "38c3510b01c175d42173c31bee4ecb99dbfa8125",
          "md5": "dee56b820fa9d93bf791c612e66e2343"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.niu",
          "module": "BasePlugin",
          "version": {
            "requires": "0.3.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "hook-method-plugin-0.3.13.jar",
          "url": "hook-method-plugin-0.3.13.jar",
          "size": 25963,
          "sha512": "46445510f8c3ac5b289fb66e36a302793befa0f8b2bfa47e6ed342185dcf16109467b95e114bd82aa6a2c8fe579d988ff79e5b62eb3ffedef3efd55482ab0ab6",
          "sha256": "96351cec57ecb453fe46bab0901f2681b155e7dee79f453899126e5e4adb1cd4",
          "sha1": "38c3510b01c175d42173c31bee4ecb99dbfa8125",
          "md5": "dee56b820fa9d93bf791c612e66e2343"
        }
      ]
    }
  ]
}
