{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "hook-method-plugin",
    "version": "0.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "hook-method-plugin-0.3.5.jar",
          "url": "hook-method-plugin-0.3.5.jar",
          "size": 26092,
          "sha512": "67bf750b437a0bf820a370885036dd02603f837c210dff2631bd278815b2307692419cc3e8c2ae6e0b7d02265a9482b06a97e94da91dc7dc3951c0795928510c",
          "sha256": "97c34b5da11ca575c3585399d512d5c7ea9148e46dc20cab1adb56f86e605c16",
          "sha1": "124c7d21d634a79c930a728acb45b99e6579de6b",
          "md5": "23ee863282ff02c7985f3fe30ad447d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.niu",
          "module": "BasePlugin",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "hook-method-plugin-0.3.5.jar",
          "url": "hook-method-plugin-0.3.5.jar",
          "size": 26092,
          "sha512": "67bf750b437a0bf820a370885036dd02603f837c210dff2631bd278815b2307692419cc3e8c2ae6e0b7d02265a9482b06a97e94da91dc7dc3951c0795928510c",
          "sha256": "97c34b5da11ca575c3585399d512d5c7ea9148e46dc20cab1adb56f86e605c16",
          "sha1": "124c7d21d634a79c930a728acb45b99e6579de6b",
          "md5": "23ee863282ff02c7985f3fe30ad447d5"
        }
      ]
    }
  ]
}
