{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "BasePlugin",
    "version": "0.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.9.jar",
          "url": "BasePlugin-0.3.9.jar",
          "size": 10659,
          "sha512": "d794e4f56d4cc82a3661f62c39850c90daaa6affd4eaa7f632db6e4fa91e782fd549b8f311d2ac1846b0968a16af0f8b8dd712d94492cb1745e4d40128d4f69e",
          "sha256": "38a20113b6ccc882f7d3991316b61be2abb0e77c8d7d04b083f17b7b74972f3e",
          "sha1": "35691f39d787e99db4d54f010d601511c7300456",
          "md5": "b0f0d589054dfb48ee35d752d74ae655"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.9.jar",
          "url": "BasePlugin-0.3.9.jar",
          "size": 10659,
          "sha512": "d794e4f56d4cc82a3661f62c39850c90daaa6affd4eaa7f632db6e4fa91e782fd549b8f311d2ac1846b0968a16af0f8b8dd712d94492cb1745e4d40128d4f69e",
          "sha256": "38a20113b6ccc882f7d3991316b61be2abb0e77c8d7d04b083f17b7b74972f3e",
          "sha1": "35691f39d787e99db4d54f010d601511c7300456",
          "md5": "b0f0d589054dfb48ee35d752d74ae655"
        }
      ]
    }
  ]
}
