{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "BasePlugin",
    "version": "0.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.13.jar",
          "url": "BasePlugin-0.3.13.jar",
          "size": 12074,
          "sha512": "d71ebe7d3e7e70175d95fdd2bd51a7448fe737f1cb89e424223c49b8508278466a4e251db6288fc57cba7e817faacd4939250933402236c7b6f47be49cb28fa1",
          "sha256": "98b2439bc999e9d48f0957aa02110e42aebd5c7f343fd60884b7e263626a16ed",
          "sha1": "e09e7f48785b88fbbf33d4ee19503f3e73e65a62",
          "md5": "ff387c710748019f8f775ff81befe17c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.13.jar",
          "url": "BasePlugin-0.3.13.jar",
          "size": 12074,
          "sha512": "d71ebe7d3e7e70175d95fdd2bd51a7448fe737f1cb89e424223c49b8508278466a4e251db6288fc57cba7e817faacd4939250933402236c7b6f47be49cb28fa1",
          "sha256": "98b2439bc999e9d48f0957aa02110e42aebd5c7f343fd60884b7e263626a16ed",
          "sha1": "e09e7f48785b88fbbf33d4ee19503f3e73e65a62",
          "md5": "ff387c710748019f8f775ff81befe17c"
        }
      ]
    }
  ]
}
