{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "BasePlugin",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.2.jar",
          "url": "BasePlugin-0.3.2.jar",
          "size": 10659,
          "sha512": "b81caf80e3322305ca826ab00ccb0da054710bafda68469d115b5b94b00cc58c883ca6c7ceaf13270d01dbf5abccafc4c91a468e9104922138c7e5d3f02d6c5f",
          "sha256": "a79f6da207c36036f455342dcaab52cdf5b8ab30b95a20ad775b40e7cf96db26",
          "sha1": "a0a366cac3b5abf7ddde35ffdd4fd10d0163c4d0",
          "md5": "e72745f4411e6675d43594ffdf59f203"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.2.jar",
          "url": "BasePlugin-0.3.2.jar",
          "size": 10659,
          "sha512": "b81caf80e3322305ca826ab00ccb0da054710bafda68469d115b5b94b00cc58c883ca6c7ceaf13270d01dbf5abccafc4c91a468e9104922138c7e5d3f02d6c5f",
          "sha256": "a79f6da207c36036f455342dcaab52cdf5b8ab30b95a20ad775b40e7cf96db26",
          "sha1": "a0a366cac3b5abf7ddde35ffdd4fd10d0163c4d0",
          "md5": "e72745f4411e6675d43594ffdf59f203"
        }
      ]
    }
  ]
}
