{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "hook-method-plugin",
    "version": "0.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "hook-method-plugin-0.3.9.jar",
          "url": "hook-method-plugin-0.3.9.jar",
          "size": 26092,
          "sha512": "6a3f36186e30605a2c2f9e8cf2a83ca64b379829f545b434fef2eac23ece3de6bf610f106551ef869c88cede71d3d9b1003ce5a6fbc394ec61b5df16a105d54d",
          "sha256": "4eaebbcf9d73fbc2a4ef4e97c835c1c6b8c3522a30884ff688399c9953afcdcb",
          "sha1": "394db29111b9390b5123dd6c939f10a40855e61b",
          "md5": "e0a6e309309ba32957fe23ae99363390"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.niu",
          "module": "BasePlugin",
          "version": {
            "requires": "0.3.9"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "hook-method-plugin-0.3.9.jar",
          "url": "hook-method-plugin-0.3.9.jar",
          "size": 26092,
          "sha512": "6a3f36186e30605a2c2f9e8cf2a83ca64b379829f545b434fef2eac23ece3de6bf610f106551ef869c88cede71d3d9b1003ce5a6fbc394ec61b5df16a105d54d",
          "sha256": "4eaebbcf9d73fbc2a4ef4e97c835c1c6b8c3522a30884ff688399c9953afcdcb",
          "sha1": "394db29111b9390b5123dd6c939f10a40855e61b",
          "md5": "e0a6e309309ba32957fe23ae99363390"
        }
      ]
    }
  ]
}
