{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "BasePlugin",
    "version": "0.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.5.jar",
          "url": "BasePlugin-0.3.5.jar",
          "size": 10659,
          "sha512": "b72ae28953e1ff940c41e887e3397a1f390a28c179e34b05322ffb16f4f3627cd7ed7d4709cc1ddd6d8eb69dd22402ce44f03e2dad68a35f304ce86db8968020",
          "sha256": "facd3c2f87e3100cf0b95f0e6b37d4338807059c21d8a0804488717df8184f75",
          "sha1": "362866bfdbb3e8fa840eefa5e9a7876dd1bdf77b",
          "md5": "33515c7c91c20206a900776dd1058203"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.5.jar",
          "url": "BasePlugin-0.3.5.jar",
          "size": 10659,
          "sha512": "b72ae28953e1ff940c41e887e3397a1f390a28c179e34b05322ffb16f4f3627cd7ed7d4709cc1ddd6d8eb69dd22402ce44f03e2dad68a35f304ce86db8968020",
          "sha256": "facd3c2f87e3100cf0b95f0e6b37d4338807059c21d8a0804488717df8184f75",
          "sha1": "362866bfdbb3e8fa840eefa5e9a7876dd1bdf77b",
          "md5": "33515c7c91c20206a900776dd1058203"
        }
      ]
    }
  ]
}
