{
  "formatVersion": "1.1",
  "component": {
    "group": "com.niu",
    "module": "BasePlugin",
    "version": "0.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.7.jar",
          "url": "BasePlugin-0.3.7.jar",
          "size": 10659,
          "sha512": "5dafc6d600c6f87e28e05f747a0b7ba0a7d9d7b5f2ee2213d39523285b226d41b523749091d07cd97f109226deaffa0f4865af86fcf5fb8dcbb182e87a776191",
          "sha256": "afa8795ba585aaa8a12c71aab88346e3a50d8726154f51e800d1a3d216ee83a3",
          "sha1": "60c714df8d2fb9946dc28a18d7950ba881609fab",
          "md5": "d5478048e1357ff8ad498180fad75a0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "BasePlugin-0.3.7.jar",
          "url": "BasePlugin-0.3.7.jar",
          "size": 10659,
          "sha512": "5dafc6d600c6f87e28e05f747a0b7ba0a7d9d7b5f2ee2213d39523285b226d41b523749091d07cd97f109226deaffa0f4865af86fcf5fb8dcbb182e87a776191",
          "sha256": "afa8795ba585aaa8a12c71aab88346e3a50d8726154f51e800d1a3d216ee83a3",
          "sha1": "60c714df8d2fb9946dc28a18d7950ba881609fab",
          "md5": "d5478048e1357ff8ad498180fad75a0e"
        }
      ]
    }
  ]
}
